using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Contracts; 

namespace DownloadData
{
   public class CreationMarks : ICreateMarks
    {
        public List<MarkItem> MarksCollection { get; set; }

        public List<Сategory> CreateCategory()
        {
           return new List<Сategory>()
            {
                new Сategory(MarkType.InParkEntertainment,"Развлечения в парке"),
                new Сategory(MarkType.ObjectForKids,"Объекты для детей"),
                new Сategory(MarkType.ObjectForOlds,"Объекты для пожилых"),
                new Сategory(MarkType.SpotsObject,"Спортивные объекты"),
                new Сategory(MarkType.CafeAndRestaurants,"Кафе и рестораны"),
                new Сategory(MarkType.NaturalArea,"Природные зоны"),
                new Сategory(MarkType.ParkingPlace,"Места парковки"),
                new Сategory(MarkType.Variety,"Эстрады"),
                new Сategory(MarkType.OpportunitiesForSelfDevelopment,"Возможности для саморазвития"),
                new Сategory(MarkType.FacilitiesForDisabledGuests,"Услуги для инвалидов"),
                new Сategory(MarkType.SportsGrounds,"Спортплощадки"),
                new Сategory(MarkType.GeneralPurposeObjects,"Объекты общего назначения"),
                new Сategory(MarkType.RentalPoints,"Пункты проката"),
                new Сategory(MarkType.ExtrimeZone,"Экстрим-зоны"),
                new Сategory(MarkType.ParkingForVisitors,"Парковки для посетителей",false),
                new Сategory(MarkType.Kamping,"Кемпинг"),
                new Сategory(MarkType.Toilets,"Туалеты",false),
                new Сategory(MarkType.ForgottenThings,"Забытые вещи",false),
                 new Сategory(MarkType.EntranceToThePark,"Вход в парк",false)
            };
        }

        public List<MarkItem> CreateMarks()
        {
            MarksCollection = new List<MarkItem>()
            {
                new MarkItem("Туалеты", "tualet1", new List<MarkType>() {MarkType.Toilets, MarkType.GeneralPurposeObjects}, "WC.png", false),
                new MarkItem("Туалеты", "tualet2", new List<MarkType>() {MarkType.Toilets, MarkType.GeneralPurposeObjects}, "WC.png",false),
                new MarkItem("Туалеты", "tualet3", new List<MarkType>() {MarkType.Toilets, MarkType.GeneralPurposeObjects}, "WC.png",false),
                new MarkItem("Туалеты", "tualet4", new List<MarkType>() {MarkType.Toilets, MarkType.GeneralPurposeObjects}, "WC.png",false),
                new MarkItem("Туалеты", "tualet5", new List<MarkType>() {MarkType.Toilets, MarkType.GeneralPurposeObjects}, "WC.png",false),
                new MarkItem("Туалеты", "tualet6", new List<MarkType>() {MarkType.Toilets, MarkType.GeneralPurposeObjects}, "WC.png",false),
                new MarkItem("Туалеты", "tualet7", new List<MarkType>() {MarkType.Toilets, MarkType.GeneralPurposeObjects}, "WC.png",false),
                new MarkItem("Туалеты", "tualet8", new List<MarkType>() {MarkType.Toilets, MarkType.GeneralPurposeObjects}, "WC.png",false),
                //new MarkItem("Туалеты", "tualet9", new List<MarkType>() {MarkType.Toilets, MarkType.GeneralPurposeObjects}, "WC.png",false),
                //new MarkItem("Туалеты", "tualet10", new List<MarkType>() {MarkType.Toilets, MarkType.GeneralPurposeObjects}, "WC.png",false),
                new MarkItem("Вход в парк", "vhod11", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                new MarkItem("Вход в парк", "vhod12", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                new MarkItem("Вход в парк", "vhod13", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                new MarkItem("Вход в парк", "vhod14", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                new MarkItem("Вход в парк", "vhod15", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                new MarkItem("Вход в парк", "vhod16", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                new MarkItem("Вход в парк", "vhod17", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                new MarkItem("Вход в парк", "vhod18", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                new MarkItem("Вход в парк", "vhod19", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                new MarkItem("Вход в парк", "vhod20", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                //new MarkItem("Вход в парк", "vhod21", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                //new MarkItem("Вход в парк", "vhod22", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                //new MarkItem("Вход в парк", "vhod23", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                //new MarkItem("Вход в парк", "vhod24", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.EntranceToThePark}, "mark.png",false),
                new MarkItem("Парковки для посетителей", "parkingposetitelei25", new List<MarkType>() {MarkType.ParkingPlace, MarkType.ParkingForVisitors}, "parking.png" ,false),
                new MarkItem("Парковки для посетителей", "parkingposetitelei26", new List<MarkType>() {MarkType.ParkingPlace, MarkType.ParkingForVisitors}, "parking.png" ,false),
                //new MarkItem("Парковки для посетителей", "parkingposetitelei27", new List<MarkType>() {MarkType.ParkingPlace, MarkType.ParkingForVisitors}, "parking.png" ,false),
                //new MarkItem("Парковки для посетителей", "parkingposetitelei28", new List<MarkType>() {MarkType.ParkingPlace, MarkType.ParkingForVisitors}, "parking.png" ,false),
                new MarkItem("Парковка для мотоциклов", "parkingposetitelei29", new List<MarkType>() {MarkType.ParkingPlace}, "parking.png"),
                //new MarkItem("Парковка для мотоциклов", "parkingposetitelei30", new List<MarkType>() {MarkType.ParkingPlace}, "parking.png"),
                new MarkItem("Забытые вещи", "zabutayveshi31", new List<MarkType>() {MarkType.GeneralPurposeObjects, MarkType.ForgottenThings}, "case.png"),
                //new MarkItem("Кемпинг", "kamping32", new List<MarkType>() {MarkType.Kamping, MarkType.InParkEntertainment}, "tent.png"),
                new MarkItem("Детский центр «Смекайка»", "detcentreskameika33", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.ObjectForKids}, "kacheli.png"),
                new MarkItem("Интерактивная музей-выставка кошек «Фелинариум»", "intermuseufelanium34", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.GeneralPurposeObjects}, "rabbit.png"),
                new MarkItem("Современный музей каллиграфии", "sovmuscollegr35", new List<MarkType>() {MarkType.InParkEntertainment,MarkType.ObjectForKids, MarkType.OpportunitiesForSelfDevelopment}, "list.png"),
                new MarkItem("Банкоматы", "bankomat36", new List<MarkType>() {MarkType.InParkEntertainment}, "creditcard.png"),
                new MarkItem("Спортивный центр «Спарк»", "spotrcentrespartak37", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SpotsObject, MarkType.SportsGrounds}, "sport.png"),
                new MarkItem("Студия танцев BEST", "studiatancevbest38", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SportsGrounds, MarkType.SpotsObject, MarkType.OpportunitiesForSelfDevelopment}, "star.png"),
                new MarkItem("Каток «Лёд»", "katokled39", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.ObjectForKids, MarkType.SpotsObject}, "sport.png"),
                new MarkItem("Коворкинг в «БуквоДоме»", "kogoworkbukvodome40", new List<MarkType>() {MarkType.InParkEntertainment}, "hernya.png"),
                new MarkItem("Букводом", "bukvodome41", new List<MarkType>() {MarkType.InParkEntertainment}, "hernya.png"),
                new MarkItem("3-й Лучевой просек", "luchevoiprocek42", new List<MarkType>() {MarkType.InParkEntertainment}, "hernya.png"),
                new MarkItem("Скандинавская ходьба", "skadinavskayhodba43", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.ObjectForOlds, MarkType.SpotsObject}, "sport.png"),
                new MarkItem("Хранение спортивного инвентаря в парке", "hraneniesportivnogoinvertorya44", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SpotsObject}, "sport.png"),
                new MarkItem("Веранда танцев", "verendatancev45", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SpotsObject, MarkType.SportsGrounds, MarkType.ObjectForOlds, MarkType.Variety}, "hernya.png"),
                new MarkItem("Клуб любителей танцев", "clublubiteleytancev46", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SpotsObject, MarkType.SportsGrounds, MarkType.ObjectForOlds}, "hernya.png"),
                new MarkItem("Аттракционы", "attracionu47", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.ObjectForKids}, "kacheli.png"),
                new MarkItem("Киоск «Пончиковая»", "kioskponchikovaya48", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.CafeAndRestaurants}, "chainik.png"),
                new MarkItem("Тир", "tir49", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.ObjectForKids}, "star.png"),
                new MarkItem("Фонтанная площадь", "fontanayploshad50", new List<MarkType>() {MarkType.InParkEntertainment}, "hernya.png"),
                new MarkItem("Горнолыжные и сноуборд-тренажеры", "gornolushnuysnoubordtrenoshurs51", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SportsGrounds, MarkType.SpotsObject, MarkType.ExtrimeZone}, "sport.png"),
                new MarkItem("Эстрада «Ротонда»", "estradarotonda52", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.Variety, MarkType.ObjectForOlds}, "star.png"),
                new MarkItem("Клуб любителей танцев", "clublubiteleytancev53", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SpotsObject, MarkType.SportsGrounds, MarkType.ObjectForOlds}, "hernya.png"),
                new MarkItem("Киоск «Кофебайк»", "kioskkofebaik54", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.CafeAndRestaurants}, "chainik.png"),
                new MarkItem("Киоск «Чешские колбаски»", "kioskcheskiekolbaski55", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.CafeAndRestaurants}, "shavuha.png"),
                new MarkItem("Контактный зоопарк «Живой уголок»", "contactnuizooparkshivoyugolok56", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.ObjectForKids}, "turtle.png"),
                new MarkItem("Сад астрономов", "sadastranomov57", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.NaturalArea, MarkType.OpportunitiesForSelfDevelopment}, "star.png"),
                new MarkItem("Банкоматы", "bankomat58", new List<MarkType>() {MarkType.InParkEntertainment}, "creditcard.png"),
                new MarkItem("Музей автомобилей ЗИЛ", "museiavto59", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.GeneralPurposeObjects}, "house.png"),
                new MarkItem("Фирменные сувениры парка «Сокольники»", "suvenirsokolniki60", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.GeneralPurposeObjects}, "photo.png"),
                new MarkItem("Ресторан здоровой еды Sekta-cafe", "restoransektacafe61", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.CafeAndRestaurants}, "vok.png"),
                new MarkItem("Школа унициклинга", "shkolaunicilinga62", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SpotsObject, MarkType.SportsGrounds}, "sport.png"),
                new MarkItem("Тир", "tir63", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.ObjectForKids}, "star.png"),
                new MarkItem("Музей «Билет в СССР»", "bilitvsssr64", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.OpportunitiesForSelfDevelopment}, "list.png"),
                new MarkItem("Тир", "tir65", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.ObjectForKids}, "star.png"),
                new MarkItem("Клуб любителей танцев", "clublubiteleytancev66", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SpotsObject, MarkType.SportsGrounds, MarkType.ObjectForOlds}, "hernya.png"),
                new MarkItem("Дом детского творчества","ddt67", new List<MarkType>() { MarkType.InParkEntertainment, MarkType.ObjectForKids}, "hernya.png"),
                new MarkItem ("Спортивный центр «Лидер»", "sportcentrelider68", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SpotsObject, MarkType.SportsGrounds}, "sport.png"),
                new MarkItem("Эстрада «Берёзки»", "estradabereski69", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.Variety}, "star.png"),
                new MarkItem("Орнитарий", "ornitarii70", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.ObjectForKids, MarkType.OpportunitiesForSelfDevelopment}, "star.png"),
                new MarkItem("Велосервис", "veloservic71", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.SportsGrounds, MarkType.SpotsObject, MarkType.GeneralPurposeObjects}, "sport.png"),
                new MarkItem("Свадьбы", "svadibu72", new List<MarkType>() {MarkType.InParkEntertainment}, "star.png"),
                new MarkItem("Золотой пруд", "zolotoiprud73", new List<MarkType>() {MarkType.InParkEntertainment, MarkType.NaturalArea}, "nature.png"),
                new MarkItem("Комната матери и ребенка", "kommat74", new List<MarkType>() {MarkType.ObjectForKids}, "WC.png"),
                new MarkItem("Детский день рождения с парком «Сокольники»", "detrosh75", new List<MarkType>() {MarkType.ObjectForKids}, "kacheli.png"),
                new MarkItem("Комната матери и ребенка", "kommat75", new List<MarkType>() {MarkType.ObjectForKids}, "WC.png"),
                new MarkItem("Шахматно-шашечный клуб", "shah76", new List<MarkType>() {MarkType.ObjectForKids, MarkType.NaturalArea, MarkType.ObjectForOlds, MarkType.SpotsObject}, "chair.png"),
                new MarkItem("Комната матери и ребенка", "kommat77", new List<MarkType>() {MarkType.ObjectForKids}, "WC.png"),
                new MarkItem("Детский день рождения с парком «Сокольники»", "detrosh76", new List<MarkType>() {MarkType.ObjectForKids}, "kacheli.png"),
                new MarkItem("Всепогорка", "vseror77", new List<MarkType>() {MarkType.ObjectForKids, MarkType.SportsGrounds, MarkType.SpotsObject}, "kacheli.png"),
                new MarkItem("Комната матери и ребенка", "kommat78", new List<MarkType>() {MarkType.ObjectForKids}, "WC.png"),
                new MarkItem("Комната матери и ребенка", "kommat79", new List<MarkType>() {MarkType.ObjectForKids}, "WC.png"),
                new MarkItem("Детский день рождения с парком «Сокольники»", "detrosh80", new List<MarkType>() {MarkType.ObjectForKids}, "kacheli.png"),
                new MarkItem("Иннопарк", "in81", new List<MarkType>() {MarkType.ObjectForKids}, "kacheli.png"),
                new MarkItem("Батутная арена", "bat82", new List<MarkType>() {MarkType.ObjectForKids, MarkType.SpotsObject, MarkType.SportsGrounds, MarkType.ExtrimeZone}, "sport.png"),
                new MarkItem("Детский день рождения с парком «Сокольники»", "detrosh83", new List<MarkType>() {MarkType.ObjectForKids}, "kacheli.png"),
                new MarkItem("Музей парка", "museiparka83", new List<MarkType>() {MarkType.ObjectForKids, MarkType.OpportunitiesForSelfDevelopment, MarkType.ObjectForOlds}, "list.png"),
                new MarkItem("Детский день рождения с парком «Сокольники»", "detrosh84", new List<MarkType>() {MarkType.ObjectForKids}, "kacheli.png"),
                new MarkItem("Комната матери и ребенка", "kommat85", new List<MarkType>() {MarkType.ObjectForKids}, "WC.png"),
                new MarkItem("Танцпол 3+", "tan86", new List<MarkType>() {MarkType.ObjectForKids, MarkType.Variety}, "star.png"),
                new MarkItem("Памятник Мойдодыру", "moi87", new List<MarkType>() {MarkType.ObjectForKids}, "time.png"),
                //new MarkItem("Комната матери и ребенка", "kommat88", new List<MarkType>() {MarkType.ObjectForKids}, "WC.png"),
                new MarkItem("Детская игровая площадка", "irg89", new List<MarkType>() {MarkType.ObjectForKids}, "kacheli.png"),
                new MarkItem("Изумрудный город", "izum90", new List<MarkType>() {MarkType.ObjectForKids}, "star.png"),
                new MarkItem("Цигун", "cigun91", new List<MarkType>() {MarkType.ObjectForOlds, MarkType.SpotsObject, MarkType.SportsGrounds}, "sport.png"),
                new MarkItem("Картинг-центр", "cart92", new List<MarkType>() {MarkType.SpotsObject, MarkType.SportsGrounds, MarkType.ExtrimeZone}, "sport.png"),
                new MarkItem("Скейт-парк", "skeit93", new List<MarkType>() {MarkType.SpotsObject, MarkType.SportsGrounds, MarkType.ExtrimeZone}, "sport.png"),
                new MarkItem("Траттория «Меркато»", "mer94", new List<MarkType>() {MarkType.CafeAndRestaurants}, "chicken.png"),
                new MarkItem("Киоск «Пян-се»", "payn95", new List<MarkType>() {MarkType.CafeAndRestaurants}, "vok.png"),
                new MarkItem("Киоск «Блинная»", "blin96", new List<MarkType>() {MarkType.CafeAndRestaurants}, "cheburek.png"),
                new MarkItem("Crafted Bar", "craft97", new List<MarkType>() {MarkType.CafeAndRestaurants}, "roll.png"),
                new MarkItem("Киоск «Стардогс»", "stardog98", new List<MarkType>() {MarkType.CafeAndRestaurants}, "shavuha.png"),
                new MarkItem("Кафе «Сирень»", "sir99", new List<MarkType>() {MarkType.CafeAndRestaurants}, "pizza.png"),
                new MarkItem("Кафе «Мельница»", "mel100", new List<MarkType>() {MarkType.CafeAndRestaurants}, "chicken.png"),
                new MarkItem("Кафе «Море внутри»", "more101", new List<MarkType>() {MarkType.CafeAndRestaurants}, "krevetki.png"),
                new MarkItem("Кемпинг", "kemp102", new List<MarkType>() {MarkType.Kamping, MarkType.NaturalArea}, "tent.png"),
                new MarkItem("Нижний Майский пруд", "may103", new List<MarkType>() {MarkType.NaturalArea}, "nature.png"),
                new MarkItem("Павильоны Конгрессно-выставочного центра «Сокольники»", "pavsokol104", new List<MarkType>() {MarkType.OpportunitiesForSelfDevelopment}, "star.png"),
                new MarkItem("Павильоны Конгрессно-выставочного центра «Сокольники»", "pavsokol105", new List<MarkType>() {MarkType.OpportunitiesForSelfDevelopment}, "star.png"),
                new MarkItem("Солнечная поляна", "solpal105", new List<MarkType>() {MarkType.OpportunitiesForSelfDevelopment}, "nature.png"),
                new MarkItem("Кинополяна", "kinopolyan106", new List<MarkType>() {MarkType.OpportunitiesForSelfDevelopment}, "star.png"),
                new MarkItem("Экскурсии", "eks107", new List<MarkType>() {MarkType.OpportunitiesForSelfDevelopment, MarkType.GeneralPurposeObjects}, "check.png"),
                new MarkItem("Экскурсии", "eks108", new List<MarkType>() {MarkType.OpportunitiesForSelfDevelopment, MarkType.GeneralPurposeObjects}, "check.png"),
                new MarkItem("Людям с ограниченными физическими возможностями", "inv109", new List<MarkType>() {MarkType.FacilitiesForDisabledGuests}, "disabled.png"),
                new MarkItem("Уличные тренажеры", "tr110", new List<MarkType>() {MarkType.SportsGrounds}, "sport.png"),
                new MarkItem("Стартовый городок", "gor111", new List<MarkType>() {MarkType.SportsGrounds}, "sport.png"),
                new MarkItem("Уличные тренажеры", "tr112", new List<MarkType>() {MarkType.SportsGrounds}, "sport.png"),
                new MarkItem("Уличные тренажеры", "tr113", new List<MarkType>() {MarkType.SportsGrounds}, "sport.png"),
                new MarkItem("Тропа здоровья", "tropa114", new List<MarkType>() {MarkType.SportsGrounds}, "sport.png"),
                new MarkItem("Площадка для проведения публичных мероприятий (Гайд-парк)", "gaid115", new List<MarkType>() {MarkType.GeneralPurposeObjects}, "check.png"),
                new MarkItem("Стойки информации и инфоматы", "inf116", new List<MarkType>() {MarkType.GeneralPurposeObjects}, "info.png"),
                new MarkItem("Стойки информации и инфоматы", "inf117", new List<MarkType>() {MarkType.GeneralPurposeObjects}, "info.png"),
                new MarkItem("Стойки информации и инфоматы", "inf118", new List<MarkType>() {MarkType.GeneralPurposeObjects}, "info.png"),
                new MarkItem("Большой круг", "krug119", new List<MarkType>() {MarkType.GeneralPurposeObjects}, "check.png"),
                new MarkItem("Стойки информации и инфоматы", "inf120", new List<MarkType>() {MarkType.GeneralPurposeObjects}, "info.png"),
                new MarkItem("Стойки информации и инфоматы", "inf121", new List<MarkType>() {MarkType.GeneralPurposeObjects}, "info.png"),
                new MarkItem("Стойки информации и инфоматы", "inf122", new List<MarkType>() {MarkType.GeneralPurposeObjects}, "info.png"),
                new MarkItem("Фестивальная площадь", "fest123", new List<MarkType>() {MarkType.GeneralPurposeObjects}, "star.png"),
                //new MarkItem("Стойки информации и инфоматы", "inf124", new List<MarkType>() {MarkType.GeneralPurposeObjects}, "info.png"),
                //new MarkItem ("Кофейня Капучинофф", "kap125", new List<MarkType> {MarkType.CafeAndRestaurants}, "icecream.png"),
                new MarkItem("Клуб любителей бильярда", "clubbiliyard126", new List<MarkType> {MarkType.InParkEntertainment, MarkType.SpotsObject}, "star.png"),
                new MarkItem("Клуб собаководов", "clubsobakovodov127", new List<MarkType> {MarkType.GeneralPurposeObjects}, "rabbit.png"),
                new MarkItem("Столы для настольного тенниса", "tennis128", new List<MarkType> {MarkType.InParkEntertainment, MarkType.SportsGrounds, MarkType.SpotsObject}, "sport.png")
            };
            return MarksCollection; 
        }
    }
}
